# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/meizu/mx4pro/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/meizu/mx4pro/proprietary/app/mcRegistry/05010000000000000000000000000000.tlbin:system/app/mcRegistry/05010000000000000000000000000000.tlbin \
    vendor/meizu/mx4pro/proprietary/app/mcRegistry/05020000000000000000000000000000.tabin:system/app/mcRegistry/05020000000000000000000000000000.tabin \
    vendor/meizu/mx4pro/proprietary/app/mcRegistry/ffffffffffff00000000000000000001.tabin:system/app/mcRegistry/ffffffffffff00000000000000000001.tabin \
    vendor/meizu/mx4pro/proprietary/app/mcRegistry/ffffffffffff00000000000000000002.tabin:system/app/mcRegistry/ffffffffffff00000000000000000002.tabin \
    vendor/meizu/mx4pro/proprietary/bin/board_info:system/bin/board_info \
    vendor/meizu/mx4pro/proprietary/bin/cploadserver:system/bin/cploadserver \
    vendor/meizu/mx4pro/proprietary/bin/eeh_server:system/bin/eeh_server \
    vendor/meizu/mx4pro/proprietary/bin/gpsd:system/bin/gpsd \
    vendor/meizu/mx4pro/proprietary/bin/gxFpDaemon:system/bin/gxFpDaemon \
    vendor/meizu/mx4pro/proprietary/bin/nvmserver:system/bin/nvmserver \
    vendor/meizu/mx4pro/proprietary/etc/firmware/audience/cvqmodels/adnc_cvq_detection_bkg.bin:system/etc/firmware/audience/cvqmodels/adnc_cvq_detection_bkg.bin \
    vendor/meizu/mx4pro/proprietary/etc/firmware/audience/cvqmodels/adnc_cvq_detection_bkg_w_hdrs.bin:system/etc/firmware/audience/cvqmodels/adnc_cvq_detection_bkg_w_hdrs.bin \
    vendor/meizu/mx4pro/proprietary/etc/firmware/audience/cvqmodels/adnc_cvq_training_bkg.bin:system/etc/firmware/audience/cvqmodels/adnc_cvq_training_bkg.bin \
    vendor/meizu/mx4pro/proprietary/etc/firmware/audience/es705/audience-es705-fw.bin:system/etc/firmware/audience/es705/audience-es705-fw.bin \
    vendor/meizu/mx4pro/proprietary/etc/firmware/audience/es705/audience-es705-vs.bin:system/etc/firmware/audience/es705/audience-es705-vs.bin \
    vendor/meizu/mx4pro/proprietary/etc/firmware/BCM4335.hcd:system/etc/firmware/BCM4335.hcd \
    vendor/meizu/mx4pro/proprietary/etc/firmware/NZ_LTG_DKBI.bin:system/etc/firmware/NZ_LTG_DKBI.bin \
    vendor/meizu/mx4pro/proprietary/etc/firmware/NZ_LTG_DL_M09_Y0_AI_SKL_Flash.bin:system/etc/firmware/NZ_LTG_DL_M09_Y0_AI_SKL_Flash.bin \
    vendor/meizu/mx4pro/proprietary/etc/firmware/NZ_LTG_DL_MEIZU_HSIC.bin:system/etc/firmware/NZ_LTG_DL_MEIZU_HSIC.bin \
    vendor/meizu/mx4pro/proprietary/etc/firmware/NZ_LTG_MDB.zip:system/etc/firmware/NZ_LTG_MDB.zip \
    vendor/meizu/mx4pro/proprietary/etc/firmware/NZ_LTG_OBMI.bin:system/etc/firmware/NZ_LTG_OBMI.bin \
    vendor/meizu/mx4pro/proprietary/etc/firmware/NZ_LWG_DKBI.bin:system/etc/firmware/NZ_LWG_DKBI.bin \
    vendor/meizu/mx4pro/proprietary/etc/firmware/NZ_LWG_DL_M09_Y0_AI_SKL_Flash.bin:system/etc/firmware/NZ_LWG_DL_M09_Y0_AI_SKL_Flash.bin \
    vendor/meizu/mx4pro/proprietary/etc/firmware/NZ_LWG_DL_MEIZU_HSIC.bin:system/etc/firmware/NZ_LWG_DL_MEIZU_HSIC.bin \
    vendor/meizu/mx4pro/proprietary/etc/firmware/NZ_LWG_MDB.zip:system/etc/firmware/NZ_LWG_MDB.zip \
    vendor/meizu/mx4pro/proprietary/etc/firmware/NZ_LWG_OBMI.bin:system/etc/firmware/NZ_LWG_OBMI.bin \
    vendor/meizu/mx4pro/proprietary/etc/firmware/Skylark_LTG.bin:system/etc/firmware/Skylark_LTG.bin \
    vendor/meizu/mx4pro/proprietary/etc/firmware/Skylark_LWG.bin:system/etc/firmware/Skylark_LWG.bin \
    vendor/meizu/mx4pro/proprietary/etc/mrvl_tel_at_def.cfg:system/etc/mrvl_tel_at_def.cfg \
    vendor/meizu/mx4pro/proprietary/etc/mrvl_tel_diag_def.cfg:system/etc/mrvl_tel_diag_def.cfg \
    vendor/meizu/mx4pro/proprietary/etc/mrvl_tel_eeh_def.cfg:system/etc/mrvl_tel_eeh_def.cfg \
    vendor/meizu/mx4pro/proprietary/etc/mrvl_tel_modemmonitor_def.cfg:system/etc/mrvl_tel_modemmonitor_def.cfg \
    vendor/meizu/mx4pro/proprietary/etc/mrvl_tel_nvmserver_def.cfg:system/etc/mrvl_tel_nvmserver_def.cfg \
    vendor/meizu/mx4pro/proprietary/etc/mtconfig.ini:system/etc/mtconfig.ini \
    vendor/meizu/mx4pro/proprietary/etc/nvm_uncheck_file.cfg:system/etc/nvm_uncheck_file.cfg \
    vendor/meizu/mx4pro/proprietary/etc/tfa98xx/coldboot.patch:system/etc/tfa98xx/coldboot.patch \
    vendor/meizu/mx4pro/proprietary/etc/tfa98xx/music_eq_0.eq:system/etc/tfa98xx/music_eq_0.eq \
    vendor/meizu/mx4pro/proprietary/etc/tfa98xx/music_eq_1.eq:system/etc/tfa98xx/music_eq_1.eq \
    vendor/meizu/mx4pro/proprietary/etc/tfa98xx/music_eq_2.eq:system/etc/tfa98xx/music_eq_2.eq \
    vendor/meizu/mx4pro/proprietary/etc/tfa98xx/music_preset_0.preset:system/etc/tfa98xx/music_preset_0.preset \
    vendor/meizu/mx4pro/proprietary/etc/tfa98xx/music_preset_1.preset:system/etc/tfa98xx/music_preset_1.preset \
    vendor/meizu/mx4pro/proprietary/etc/tfa98xx/music_preset_2.preset:system/etc/tfa98xx/music_preset_2.preset \
    vendor/meizu/mx4pro/proprietary/etc/tfa98xx/MZ_M76_speaker.speaker:system/etc/tfa98xx/MZ_M76_speaker.speaker \
    vendor/meizu/mx4pro/proprietary/etc/tfa98xx/speech_eq.eq:system/etc/tfa98xx/speech_eq.eq \
    vendor/meizu/mx4pro/proprietary/etc/tfa98xx/speech_preset.preset:system/etc/tfa98xx/speech_preset.preset \
    vendor/meizu/mx4pro/proprietary/etc/tfa98xx/TFA9890_N1B12_N1C3_v3.config:system/etc/tfa98xx/TFA9890_N1B12_N1C3_v3.config \
    vendor/meizu/mx4pro/proprietary/etc/tfa98xx/TFA9890_N1C3_2_1_1.patch:system/etc/tfa98xx/TFA9890_N1C3_2_1_1.patch \
    vendor/meizu/mx4pro/proprietary/etc/TTPCom_NRAM2_ABMM_WRITEABLE_DATA_CUC.gki:system/etc/TTPCom_NRAM2_ABMM_WRITEABLE_DATA_CUC.gki \
    vendor/meizu/mx4pro/proprietary/etc/TTPCom_NRAM2_ABMM_WRITEABLE_DATA.gki:system/etc/TTPCom_NRAM2_ABMM_WRITEABLE_DATA.gki \
    vendor/meizu/mx4pro/proprietary/etc/wifi/bcmdhd.cal:system/etc/wifi/bcmdhd.cal \
    vendor/meizu/mx4pro/proprietary/lib/hw/flp.default.so:system/lib/hw/flp.default.so \
    vendor/meizu/mx4pro/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/meizu/mx4pro/proprietary/lib/hw/sensors.m76.so:system/lib/hw/sensors.m76.so \
    vendor/meizu/mx4pro/proprietary/lib/libcaFingerPrintShared.so:system/lib/libcaFingerPrintShared.so \
    vendor/meizu/mx4pro/proprietary/lib/libfp_client.so:system/lib/libfp_client.so \
    vendor/meizu/mx4pro/proprietary/lib/libfpservice.so:system/lib/libfpservice.so \
    vendor/meizu/mx4pro/proprietary/lib/libhal.so:system/lib/libhal.so \
    vendor/meizu/mx4pro/proprietary/lib/libload_lib.so:system/lib/libload_lib.so \
    vendor/meizu/mx4pro/proprietary/lib/libmarvell-ril.so:system/lib/libmarvell-ril.so \
    vendor/meizu/mx4pro/proprietary/lib/libmtel.so:system/lib/libmtel.so \
    vendor/meizu/mx4pro/proprietary/lib/libopencv_java.so:system/lib/libopencv_java.so \
    vendor/meizu/mx4pro/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/meizu/mx4pro/proprietary/lib/libvcm.so:system/lib/libvcm.so \
    vendor/meizu/mx4pro/proprietary/vendor/firmware/73BIEB1.img:system/vendor/firmware/73BIEB1.img \
    vendor/meizu/mx4pro/proprietary/vendor/firmware/73BIEBS1.img:system/vendor/firmware/73BIEBS1.img \
    vendor/meizu/mx4pro/proprietary/vendor/firmware/73TPKB1.img:system/vendor/firmware/73TPKB1.img \
    vendor/meizu/mx4pro/proprietary/vendor/firmware/73TPKOBS1.img:system/vendor/firmware/73TPKOBS1.img \
    vendor/meizu/mx4pro/proprietary/vendor/firmware/73TPKW1.img:system/vendor/firmware/73TPKW1.img \
    vendor/meizu/mx4pro/proprietary/vendor/firmware/76BIEB1.img:system/vendor/firmware/76BIEB1.img \
    vendor/meizu/mx4pro/proprietary/vendor/firmware/76BIEBS1.img:system/vendor/firmware/76BIEBS1.img \
    vendor/meizu/mx4pro/proprietary/vendor/firmware/76TPKB1.img:system/vendor/firmware/76TPKB1.img \
    vendor/meizu/mx4pro/proprietary/vendor/firmware/76TPKBS2.img:system/vendor/firmware/76TPKBS2.img \
    vendor/meizu/mx4pro/proprietary/vendor/firmware/76TPKBS.img:system/vendor/firmware/76TPKBS.img \
    vendor/meizu/mx4pro/proprietary/vendor/firmware/76TPKOBS1.img:system/vendor/firmware/76TPKOBS1.img \
    vendor/meizu/mx4pro/proprietary/vendor/firmware/76TPKW1.img:system/vendor/firmware/76TPKW1.img \
    vendor/meizu/mx4pro/proprietary/vendor/firmware/76TPKW.img:system/vendor/firmware/76TPKW.img \
    vendor/meizu/mx4pro/proprietary/vendor/firmware/76TPKWS2.img:system/vendor/firmware/76TPKWS2.img \
    vendor/meizu/mx4pro/proprietary/vendor/firmware/76WTKB1.img:system/vendor/firmware/76WTKB1.img \
    vendor/meizu/mx4pro/proprietary/vendor/firmware/76WTKB.img:system/vendor/firmware/76WTKB.img \
    vendor/meizu/mx4pro/proprietary/vendor/firmware/fimc_is_fw2.bin:system/vendor/firmware/fimc_is_fw2.bin \
    vendor/meizu/mx4pro/proprietary/vendor/firmware/hevc_fw.bin:system/vendor/firmware/hevc_fw.bin \
    vendor/meizu/mx4pro/proprietary/vendor/firmware/libpn547_fw.so:system/vendor/firmware/libpn547_fw.so \
    vendor/meizu/mx4pro/proprietary/vendor/firmware/m76-tp.img:system/vendor/firmware/m76-tp.img \
    vendor/meizu/mx4pro/proprietary/vendor/firmware/mfc_fw.bin:system/vendor/firmware/mfc_fw.bin \
    vendor/meizu/mx4pro/proprietary/vendor/firmware/seiren_fw_dram.bin:system/vendor/firmware/seiren_fw_dram.bin \
    vendor/meizu/mx4pro/proprietary/vendor/firmware/seiren_fw_sram.bin:system/vendor/firmware/seiren_fw_sram.bin \
    vendor/meizu/mx4pro/proprietary/vendor/firmware/setfile_imx220.bin:system/vendor/firmware/setfile_imx220.bin \
    vendor/meizu/mx4pro/proprietary/vendor/firmware/setfile_ov5693.bin:system/vendor/firmware/setfile_ov5693.bin \
    vendor/meizu/mx4pro/proprietary/vendor/firmware/st_fts.bin:system/vendor/firmware/st_fts.bin \
    vendor/meizu/mx4pro/proprietary/vendor/lib/egl/gpr_list.cfg:system/vendor/lib/egl/gpr_list.cfg \
    vendor/meizu/mx4pro/proprietary/vendor/lib/egl/libGLES_mali.so:system/vendor/lib/egl/libGLES_mali.so \
    vendor/meizu/mx4pro/proprietary/vendor/lib/libbt-vendor.so:system/vendor/lib/libbt-vendor.so \
    vendor/meizu/mx4pro/proprietary/vendor/lib/libmalicore.bc:system/vendor/lib/libmalicore.bc
